### ISSUE TITLE
Will this still work with vue-2.4+

### ISSUE THREAD

**Issue by imylomylo** [emilniklas/vue-dart#2]
Hi,

Dart (& Flutter) have caught my attention and would like to know if this dart package is still supported/works/final etc.?

Cheers
Mylo

**Comment by emilniklas** [comment]
Hey Milo.

I’m afraid this is an abandoned project since a long time, and it never really was made usable. If anyone wants to take the package name (`vue`), I’d be happy to give it up.

**Comment by imylomylo** [comment]
Hmmmmm thanks.
Is it a good starting point to learn about the integration process?

Thanks for prompt reply earlier.

**Comment by emilniklas** [comment]
With ”integration process”, I assume you mean JS interop, in which case I’m sure there are better resources out there. Check out ”package:js” documentation.

**Comment by imylomylo** [comment]
Ok.  Thanks for suggestion, will be in touch if Vue name in dart package needs an active project naming handover ceremony :)

Cheers Emil

**Comment by emilniklas** [comment]
👋🙂

**Comment by refi64** [comment]
Hello!

So I created [some newer Vue bindings](https://refi64.com/vuedart/), and a question: could I have the Vue package name?

Right now I'm using vue2, but that's probably going to bite me in the butt when Vue 3.0 comes out...

**Comment by emilniklas** [comment]
@kirbyfan64 yes!
I’m slightly unsure how it works, but i’ll check on pub

**Comment by emilniklas** [comment]
@kirbyfan64 The email rymg19@gmail.com now has publisher access to the `vue` name. Let me know if that's the wrong address. 😄

**Comment by refi64** [comment]
It's perfect! Thanks!!
